auto: true
title: "尹海施"
public_url: "http://sysucici.github.com"
keywords: "mono, ios, android, silverlight, asp.net mvc, asp.net web api, nhibernate, c, sql server, xml, linux, mac osx"
owner:
  name: "尹海施"
  mail: "583869582@qq.com"
disqus:
  short_name: "sysucici-github"
paginate: 10
exclude: [start-jekyll.bat, Github.sln, Github.v11.suo]